---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
    exclude_fingerprints:
      - 2948d76f42889cf4445fa2c62d7d07b6
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- tests/
- vendor/
